# ***Mathematical Operations***

### Sum of arrays

In [ ]:
import numpy as np
arr1= np.random.randint(1,10,[3,3])
arr2=np.random.randint(1,10,[3,3])
arr1 + arr2

array([[15,  4, 12],
       [ 9, 10, 10],
       [14, 10, 10]], dtype=int32)

### Exponential of each array elements

In [25]:
arr2 ** 2

array([[64,  1, 25],
       [64, 49, 36],
       [49,  4, 81]], dtype=int32)

### .sqrt() to find root of each array element

In [26]:
np.sqrt(arr2)

array([[2.82842712, 1.        , 2.23606798],
       [2.82842712, 2.64575131, 2.44948974],
       [2.64575131, 1.41421356, 3.        ]])

### .floor() to convert each element into lowest integer value

In [27]:
np.floor(arr2)

array([[8, 1, 5],
       [8, 7, 6],
       [7, 2, 9]], dtype=int32)

### .ceil() to convert each element into higher integer value

In [28]:
np.ceil(arr2)

array([[8, 1, 5],
       [8, 7, 6],
       [7, 2, 9]], dtype=int32)

### .round() to find the round figure value  

In [32]:
np.round(arr2)
np.round(arr1)

array([[7, 3, 7],
       [1, 3, 4],
       [7, 8, 1]], dtype=int32)

### .concatenate() to join two 1D arrays

In [46]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
np.concatenate((b,a))

array([4, 5, 6, 7, 1, 2, 3, 4])

### .vstack() to join 2D array vertically

In [39]:
np.vstack((arr1,arr2))

array([[7, 3, 7],
       [1, 3, 4],
       [7, 8, 1],
       [8, 1, 5],
       [8, 7, 6],
       [7, 2, 9]], dtype=int32)

### .hstack() to join 2D array horizontally

In [40]:
np.hstack((arr2,arr1))

array([[8, 1, 5, 7, 3, 7],
       [8, 7, 6, 1, 3, 4],
       [7, 2, 9, 7, 8, 1]], dtype=int32)

### .flatten() convert multi dimensional array into 1D

In [45]:
arr1.flatten()

array([7, 3, 7, 1, 3, 4, 7, 8, 1], dtype=int32)

### .split() to split 1D array into given parts

In [50]:
a=np.array([1,2,3,4])
np.split(a,2)

[array([1, 2]), array([3, 4])]

### .hsplit() split the 2D array horizontally

In [51]:
arr1= np.array([[1,2,3,3],[4,5,6,6]])
np.hsplit(arr1,2)

[array([[1, 2],
        [4, 5]]),
 array([[3, 3],
        [6, 6]])]

### .vsplit() split the 2D array vertically

In [52]:
arr1= np.array([[1,2,3,3],[4,5,6,6]])
np.vsplit(arr1,2)

[array([[1, 2, 3, 3]]), array([[4, 5, 6, 6]])]

### .where() returns the index of given condition

In [53]:
a = np.array([1,2,2,3,4])
np.where(a==2)

(array([1, 2]),)

In [54]:
a = np.array([1,2,2,3,4])
np.where(a>2)

(array([3, 4]),)

In [62]:
arr1= np.array([[1,2,3,3],[4,5,2,6]])
np.where(arr1==3)

(array([0, 0]), array([2, 3]))

### .sort() to sort the array

In [ ]:
np.sort(a)

array([4, 3, 2, 2, 1])

In [ ]:
np.sort(a)[::-1] 

array([4, 3, 2, 2, 1])

In [66]:
np.sort(arr1)

array([[1, 2, 3, 3],
       [2, 4, 5, 6]])

In [67]:
np.sort(arr1)[::-1]

array([[2, 4, 5, 6],
       [1, 2, 3, 3]])

# ***Aggregating & Statistical Function***

In [68]:
np.sum(arr1)

np.int64(26)

In [69]:
np.mean(arr1)

np.float64(3.25)

In [70]:
np.median(arr1)

np.float64(3.0)

In [71]:
np.max(arr1)

np.int64(6)

In [72]:
np.min(arr1)

np.int64(1)

In [73]:
np.std(arr1)

np.float64(1.5612494995995996)

In [74]:
np.var(arr1)

np.float64(2.4375)

### row wise sum

In [75]:
np.sum(arr1 ,axis=1)

array([ 9, 17])

### column wise sum

In [76]:
np.sum(arr1 ,axis=0)

array([5, 7, 5, 9])