In [1]:
import numpy as np

In [ ]:
dir(np)

#  ***Creating an Array***

In [5]:
l=[1,4,5,6]
arr = np.array(l)
print(type(arr))

<class 'numpy.ndarray'>


### array is also called vector in math

In [ ]:
two_d_arr = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(two_d_arr)

### Two dimensional array is called matrix
### .zeros for creating array of zeros

In [ ]:
a = np.zeros(5) 
a

array([0., 0., 0., 0., 0.])

### .ones for creating the array of ones

In [10]:
a = np.ones(5) 
a

array([1., 1., 1., 1., 1.])

### .eye for creating identity matrix of given size

In [11]:
a4 =np.eye(2)
a4

array([[1., 0.],
       [0., 1.]])

### .zeros with given dimensional

In [12]:
ar1 = np.zeros([4,3])
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### .ones with given dimensional    


In [13]:
ar2 = np.ones([2,4])
ar2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### .arange to create vector of particular range

In [14]:
ar3 = np.arange(9)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### .arange(start ,end ,steps) 

In [15]:
ar4 = np.arange(1,6)
ar4

array([1, 2, 3, 4, 5])

In [16]:
ar4 = np.arange(1,9,3)
ar4

array([1, 4, 7])

### .linespace(start,end, step) to generate random number between given range

In [17]:
ar5 = np.linspace(1,10,5)
ar5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### .full(length, number) to create the full list of given number

In [18]:
ar5 = np.full(3,8)
ar5

array([8, 8, 8])

### .full(dimension,number) to create a matrix of particular number

In [19]:
ar6 = np.full([3,3],5)
ar6

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### .random.rand(length or dimension) to create the vector or matrix or random number

In [21]:
ar6 = np.random.rand(4)
ar6

array([0.94273443, 0.55702068, 0.20039081, 0.64385693])

In [20]:
ar6 = np.random.rand(3,4)
ar6

array([[0.90161129, 0.22467915, 0.2956582 , 0.36238567],
       [0.14248967, 0.06571695, 0.14646896, 0.94078849],
       [0.64687219, 0.74249334, 0.34395145, 0.37628583]])

### .random.randint(length or dimension) to create random integer

In [23]:
num= np.random.randint(5)
num

4

In [24]:
num= np.random.randint(5,8)
num

7

### .random.randint(start,end, length or dimension) to create random integer

In [27]:
arr= np.random.randint(1,10,2)
arr

array([1, 6], dtype=int32)

In [28]:
arr= np.random.randint(1,10,[2,2])
arr

array([[5, 5],
       [1, 1]], dtype=int32)

# ***Indexing of Array***

In [29]:
arr= np.random.randint(1,10,[3,3])
arr

array([[7, 9, 7],
       [5, 5, 3],
       [7, 2, 1]], dtype=int32)

In [30]:
print(arr[0][1])

9


In [31]:
print(arr[2][0])

7


# ***Slicing of Array***

In [32]:
arr= np.random.randint(1,10,[3,3])
arr

array([[3, 5, 5],
       [2, 8, 5],
       [4, 8, 2]], dtype=int32)

### arr[row, col]

In [ ]:
arr[0:2,2] 

array([5, 5], dtype=int32)

In [34]:
arr[0:,1]

array([5, 8, 8], dtype=int32)

In [35]:
arr[1,0:2]

array([2, 8], dtype=int32)

In [36]:
arr[0:,1:]

array([[5, 5],
       [8, 5],
       [8, 2]], dtype=int32)

# ***Shape, Size & DataTypes of Array***

### shape to print the size of array

In [39]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [37]:
arr= np.random.randint(1,10,[3,3])
arr

array([[8, 5, 8],
       [5, 3, 3],
       [1, 4, 5]], dtype=int32)

In [40]:
arr.shape

(3, 3)

### size() to print the number of elements

In [41]:
arr.size

9

In [42]:
a.size

6

### .dtype() to know the data type

#### python automatically changes the size of element for vector and matrix

In [43]:
a.dtype

dtype('int64')

In [44]:
arr.dtype

dtype('int32')

# ***Mathematical Operations***

### L1 + L2 : concat the list

### npArr1+npArr2: creates a new array by summing up each elements 